events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Definición del clúster de balanceo para el Frontend (Alta Disponibilidad / Concurrencia)
    # Distribuye el tráfico Round Robin entre ambas instancias replicadas
    upstream frontend_cluster {
        server frontend-app-1:80;
        server frontend-app-2:80;
    }

    server {
        listen 80;
        server_name localhost;

        # Compresión GZIP de alta eficiencia
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

        # 1. Enrutar peticiones al clúster de Frontend
        location / {
            proxy_pass http://frontend_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Encabezados de diagnóstico opcionales para ver qué servidor Nginx interno respondió
            add_header X-Proxy-Cluster-Node $upstream_addr;
        }

        # 2. Enrutar peticiones del API al Backend Spring Boot
        location /api {
            proxy_pass http://api-backend:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Deshabilitar almacenamiento en caché de API
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
        }
    }
}
