# Configuración básica de la aplicación
spring.application.name=urbanview-api
server.port=8080

# Conexión predeterminada a la base de datos (con variables de entorno e inicialización por defecto)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/urbanview_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgrespassword}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración de logs para ver transacciones
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
